--function SCR_EVENT170927_DAYCHECK_DIALOG(self,pc)
--    if GetServerNation() ~= 'JP' then
--        return
--    end
--    
--    local now_time = os.date('*t')
--    local yday = now_time['yday']
--    local aObj = GetAccountObj(pc)
--    local reward = {
--    {1, 'Event_Drug_Alche_HP15', 20, 'Event_Drug_Alche_SP15', 20},{2, 'RestartCristal', 3, 'Premium_WarpScroll_14d', 3},
--    {3, 'Premium_boostToken_14d', 2, 'Premium_repairPotion', 3},{4, 'Premium_indunReset_14d', 1, 'Mic', 5},
--    {5, 'Event_ArborDay_Costume_Box', 1},{6, 'GIMMICK_Drug_PMATK1', 10, 'GIMMICK_Drug_PMDEF1', 10},
--    {7, 'Moru_Event160929_14d', 4, 'Drug_Haste1_event', 5},{8, 'card_Xpupkit01_event', 1},
--    {9, 'Premium_Enchantchip14', 3 , 'misc_gemExpStone_randomQuest3_14d', 1},{10, 'Premium_Enchantchip14', 3, 'Moru_Silver', 1},
--    {11, 'Event_Drug_Alche_HP15', 20, 'Event_Drug_Alche_SP15', 20},{12, 'RestartCristal', 3, 'Premium_WarpScroll_14d', 3},
--    {13, 'misc_gemExpStone_randomQuest4_14d', 1},{14, 'Premium_boostToken_14d', 2, 'Premium_repairPotion', 3},
--    {15, 'Ability_Point_Stone_500', 1},{16, 'Premium_eventTpBox_33', 1, 'egg_012', 1}
--    }
--    
--    selectMsg1 = ScpArgMsg('EVENT_170427_DAYCHECK_MSG1','COUNT1',aObj.NPC_EVENT_JP_DAY_CHECK_2)     
--    local select = ShowSelDlg(pc, 0, 'NPC_EVENT_JP_DAY_CHECK_1', selectMsg1, ScpArgMsg("Auto_DaeHwa_JongLyo"))   
--        if select == 1 then
--            if aObj.NPC_EVENT_JP_DAY_CHECK_1 ~= yday then
--                for i = 1, table.getn(reward) do
--                    if reward[i][1] == aObj.NPC_EVENT_JP_DAY_CHECK_2 + 1 then
--                        local result = i
--                        local tx = TxBegin(pc)
--                        TxSetIESProp(tx, aObj, 'NPC_EVENT_JP_DAY_CHECK_1', yday)
--                        TxSetIESProp(tx, aObj, 'NPC_EVENT_JP_DAY_CHECK_2', aObj.NPC_EVENT_JP_DAY_CHECK_2 + 1)
--                        for j = 2, #reward[result], 2 do
--                            TxGiveItem(tx, reward[result][j], reward[result][j+1], 'EV170711_TODAY_NUMBER');
--                        end
--                        local ret = TxCommit(tx)
--                        ShowOkDlg(pc, 'NPC_EVENT_JP_DAY_CHECK_2', 1)
--                        break
--                    end
--                end
--            else
--                ShowOkDlg(pc, 'NPC_EVENT_TODAY_NUMBER_5', 1)
--            end
--        end
--end