--function SCR_DAYQUEST_RANDOM_EV_DIALOG(self, pc)
--  if pc.Lv < 50 then
--    return
--  end
--    
--  local select = ShowSelDlg(pc, 0, 'EV_DAILYBOX_SEL', ScpArgMsg("Auto_DaeHwa_JongLyo"), ScpArgMsg("DayQuest_Rand_Desc02"), ScpArgMsg("DayQuest_Rand_Desc03"))
--  
--  if select == 1 or select == nil then
--    return
--  elseif select == 2 then
--    local attribute = {'Dark', 'Poison', 'Fire', 'Lightning', 'Ice', 'Earth'} -- EVENT_STRING_SOBJ01
--    local RaceType = {'Forester', 'Klaida', 'Widling', 'Paramune', 'Velnias'} -- EVENT_STRING_SOBJ02
--    local chLV = pc.Lv -- EVENT_VALUE_SOBJ09
--    local sObj = GetSessionObject(pc, 'ssn_klapeda')
--    local now_time = os.date('*t')
--    local yday = now_time['yday'] -- EVENT_VALUE_SOBJ10
--    local invent = GetInvItemCount(pc, 'EVENT_MONSTER_ITEM1')
--  
--    if sObj.EVENT_VALUE_SOBJ12 ~= 170927 then
--        local tx = TxBegin(pc)
--        TxSetIESProp(tx, sObj, 'EVENT_VALUE_SOBJ12', 170927);
--        TxSetIESProp(tx, sObj, 'EVENT_VALUE_SOBJ10', 0);
--        TxSetIESProp(tx, sObj, 'EVENT_VALUE_SOBJ09', 0);
--        TxSetIESProp(tx, sObj, 'EVENT_STRING_SOBJ02', 'None');
--        local ret = TxCommit(tx)
--    end
--
--    -- quest lv
--    chLV = chLV - 20
--    if chLV <= 1 then
--      chLV = 1
--    end
--  
--    -- day check
--    if sObj.EVENT_VALUE_SOBJ10 == yday then
--      ShowOkDlg(pc, 'NPC_EVENT_DAYQUEST_RAND01', 1)
--      return
--    end
--  
--    if sObj.EVENT_STRING_SOBJ02 == 'None' and sObj.EVENT_VALUE_SOBJ09 == 0 then -- quest start
--      local rand1 = IMCRandom(1, 6)
--      local rand2 = IMCRandom(1, 5)
--      print(attribute[rand1], RaceType[rand2])
--      local tx = TxBegin(pc)
--      --TxSetIESProp(tx, sObj, 'EVENT_STRING_SOBJ01', attribute[rand1])
--      TxSetIESProp(tx, sObj, 'EVENT_STRING_SOBJ02', RaceType[rand2])
--      TxSetIESProp(tx, sObj, 'EVENT_VALUE_SOBJ09', chLV)
--      TxGiveItem(tx, 'Drug_DayQuest_Rand', 1, "DayQuest_Start")
--      local ret = TxCommit(tx)
--    end
--  elseif select == 3 then
--    local sObj = GetSessionObject(pc, 'ssn_klapeda')
--    local now_time = os.date('*t')
--    local yday = now_time['yday'] -- EVENT_VALUE_SOBJ10
--    local invent = GetInvItemCount(pc, 'EVENT_MONSTER_ITEM1')
--    if invent >= 10 then -- reward
--      local rewardlv = sObj.EVENT_VALUE_SOBJ09 + 20
--      local cubeName = ''
--      local rewardCube = {
--        {50, 'Event_170404_1'},
--        {101, 'Event_170404_2'},
--        {151, 'Event_170404_3'},
--        {201, 'Event_170404_4'},
--        {251, 'Event_170404_5'},
--        {301, 'Event_170404_6'}
--      }
--      
--      for i = table.getn(rewardCube), 1, -1 do
--        if rewardlv >= rewardCube[i][1] then
--          cubeName = rewardCube[i][2]
--          break
--        end
--      end
--      
--      local tx = TxBegin(pc)
--      --TxSetIESProp(tx, sObj, 'EVENT_STRING_SOBJ01', 'None')
--      TxSetIESProp(tx, sObj, 'EVENT_STRING_SOBJ02', 'None')
--      TxSetIESProp(tx, sObj, 'EVENT_VALUE_SOBJ09', 0)
--      TxSetIESProp(tx, sObj, 'EVENT_VALUE_SOBJ10', yday)
--      TxGiveItem(tx, cubeName, 1, "DayQuest_Reward");
--      TxTakeItem(tx, 'EVENT_MONSTER_ITEM1', invent, "DayQuest_Take")
--      TxTakeItem(tx, 'Drug_DayQuest_Rand', 1, "DayQuest_Take")
--      local ret = TxCommit(tx)
--    end
--  end
--end
--
--function DAYQUEST_TAGETMON_CHECK(self, sObj, msg, argObj, argStr, argNum)
--  --local attribute = {'Dark', 'Poison', 'Fire', 'Lightning', 'Ice', 'Earth'} -- EVENT_VALUE_SOBJ07
--  local RaceType = {'Forester', 'Klaida', 'Widling', 'Paramune', 'Velnias'} -- EVENT_VALUE_SOBJ08
--  local sObj = GetSessionObject(self, 'ssn_klapeda')
--  local rand = IMCRandom(1, 10)
--  
--  if sObj.EVENT_STRING_SOBJ02 == 'None' or sObj.EVENT_VALUE_SOBJ09 == 0 then
--    return
--  end
--  
--  if argObj.RaceType == sObj.EVENT_STRING_SOBJ02 and sObj.EVENT_VALUE_SOBJ09 <= argObj.Lv and rand <= 2 then
----    local x, y, z = GetPos(argObj);
----    local itemObj = CreateGCIES('Monster', 'EVENT_MONSTER_ITEM1');
----    CreateItem(self, itemObj, x, y, z, 0, 5);
--      local tx = TxBegin(self)
--      TxGiveItem(tx, 'EVENT_MONSTER_ITEM1', 1, "DayQuest");
--      local ret = TxCommit(tx)
--  end
--end